# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter build and push release

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v2
        with:
         channel: 'beta'
          
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/runner/Release/*"
          tag: v1.0.${{ github.run_number }}
          token: secrets.TOKEN
